# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture_pic',
            new_name='profile_pics',
        ),
    ]
